# Generated by Django 3.2.10 on 2022-08-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='CandidateId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CandidateApp.candidatedetails'),
        ),
        migrations.AlterField(
            model_name='techskills',
            name='CandidateId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CandidateApp.candidatedetails'),
        ),
    ]
